### ISSUE TITLE
Typography Tab missing

### ISSUE THREAD

**Issue by thorayork** [wpexplorer/wpex-today#3]
Hello. I downloaded Today - this amazing theme, and in the description on WP-Explorer under Typography, it says there is a Typography tab in customizer, where you can customize fonts, sizes, etc. Unfortunately, I don't see it in my install.
Can someone help?
Thank you!

**Comment by thorayork** [comment]
@wpexplorer

**Comment by wpexplorer** [comment]
@thorayork - Sorry about the confusion! You are right this theme doesn't have typography settings in the Customizer. I will fix the description.

Some of my old items did have typography settings in the Customizer but it's actually more efficient to use a plugin for this in these free themes to keep the code slimmer.

Plugins like this should work well with the theme: https://www.wpexplorer.com/wordpress-css-live-editor-plugins/ - these will allow you not only to tweak typography but other styles as well.

If you do have any issues using a plugin let me know though.

**Comment by wpexplorer** [comment]
edit: I double checked the page - https://www.wpexplorer.com/today-free-wordpress/ - and didn't see any mention of Typography so if you can let me know where you saw that, it would be fantastic, thanks!

**Comment by thorayork** [comment]
Hi 😊 Thanks a bunch for replying. I created a child theme and if I manage to do all my desired customization, will definitely use Today.
Off topic: Fresh and Clean is one of my favorite oldest ones. I only now learned it was yours. 😊

Anyway. The typography is not in the description itself but in the theme demo. In the menu there is a parent page Features and subpage Typography. And as it was in this theme's demo, I supposed it is about Today
https://demo.wpexplorer.com/today/typography/

**Comment by thorayork** [comment]
P. S. Today is very beautiful theme. Thank you!

**Comment by wpexplorer** [comment]
Thank you so much for the note, I will update the demo!

I actually plan on making many more free themes this year, I'm finishing up a redesign of wpexplorer.com and then I am updating all the current themes and making new ones. So if you have any specific suggestions for themes to make, let me know. I'm always curious to see what people are looking for and what they like.

- AJ

**Comment by thorayork** [comment]
I am a die hard classic blog themes lover, so may be I am not the best person to ask. The cleaner, the more minimal and classic blog, the better in my opinion. But people now are spoiled from the abundance of everything.. So I don't really know what to suggest. Most of your themes are really my style, so I guess work from the heart what comes to you as a theme artist 😊
Thank you once again for replying and for all your work ❤️
I will mark it closed, yes?

**Comment by thorayork** [comment]
@wpexplorer Just in case you come to read the messages. Unfortunately, I will not be able to use Today, because I want site in Russian, but I cannot translate it neither with Poedit, nor with Loco translate. It doesn't let me 🤔😔

**Comment by wpexplorer** [comment]
@thorayork - just pushed out version 1.3, if you have any other issues though feel free to let me know!

https://github.com/wpexplorer/wpex-today/releases
https://www.wpexplorer.com/today-free-wordpress/

**Comment by thorayork** [comment]
@wpexplorer I don't mean to clog the thread but just to let you know that I saw your messages.
After work I will try to set everything up and will let you know how it went!

Thank you! 😊
